### PR TITLE
Do not require list for declaring multiple dependencies.

### PR DESCRIPTION
**Pull request by salkinium**
Cos it's nicer to write 
```
module.depends(":platform:core", ":platform:clock.generic")
```
instead of 
```
module.depends([":platform:core", ":platform:clock.generic"])
```
cc @dergraaf 

I made it backwards compatible, do you want that? I'm changing all multiple dependency declarations in modm anyways.

### CODE REVIEW

**Comment by salkinium** [comment]
Oh, gee, there are a lot of places where a list is used in modm, even for single dependencies…

**Comment by salkinium** [comment]
See changes to modm: https://github.com/modm-io/modm/commit/8c0631c7a105245a2e4db2a7a678dec658743f50

**Comment by dergraaf** [comment]
I like it! Actually I was also thinking about changing that after finding myself writing dependencies as multiple arguments and wondering why it was not working.

> I made it backwards compatible, do you want that?

Dropping the list part completely is better. You can always use `*list` if you have a list you want to pass into the function.

**Comment by dergraaf** [comment]
@salkinium Can you also update the lbuild tests? See https://travis-ci.org/dergraaf/library-builder/builds/196376245

**Comment by salkinium** [comment]
We… we have tests? 😳

**Comment by dergraaf** [comment]
> We… we have tests?

Yes, since quite a while. The CI part since today :smile:

**Pull request merged**
